In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

loading the dataset

In [2]:
df=pd.read_csv('Screen_Time.csv')
df.head()

,Age,Gender,Avg_Daily_Screen_Time_hr,Primary_Device,Exceeded_Recommended_Limit,Educational_to_Recreational_Ratio,Health_Impacts,Urban_or_Rural
0,14,Male,3.99,Smartphone,True,0.42,"Poor Sleep, Eye Strain",Urban
1,11,Female,4.61,Laptop,True,0.30,Poor Sleep,Urban
2,18,Female,3.73,TV,True,0.32,Poor Sleep,Urban
3,15,Female,1.21,Laptop,False,0.39,NaN,Urban
4,12,Female,5.89,Smartphone,True,0.49,"Poor Sleep, Anxiety",Urban

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9712 entries, 0 to 9711
Data columns (total 8 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                9712 non-null   int64
 1   Gender                             9712 non-null   object
 2   Avg_Daily_Screen_Time_hr           9712 non-null   float64
 3   Primary_Device                     9712 non-null   object
 4   Exceeded_Recommended_Limit         9712 non-null   bool
 5   Educational_to_Recreational_Ratio  9712 non-null   float64
 6   Health_Impacts                     6494 non-null   object
 7   Urban_or_Rural                     9712 non-null   object
dtypes: bool(1), float64(2), int64(1), object(4)
memory usage: 540.7+ KB

In [4]:
df.describe()

,Age,Avg_Daily_Screen_Time_hr,Educational_to_Recreational_Ratio
count,9712.000000,9712.000000,9712.000000
mean,12.979201,4.352837,0.427226
std,3.162437,1.718232,0.073221
min,8.000000,0.000000,0.300000
25%,10.000000,3.410000,0.370000
50%,13.000000,4.440000,0.430000
75%,16.000000,5.380000,0.480000
max,18.000000,13.890000,0.600000

In [5]:
df.isnull().sum()

Age                                     0
Gender                                  0
Avg_Daily_Screen_Time_hr                0
Primary_Device                          0
Exceeded_Recommended_Limit              0
Educational_to_Recreational_Ratio       0
Health_Impacts                       3218
Urban_or_Rural                          0
dtype: int64

In [6]:
df.fillna("None", inplace=True)

In [7]:
df.isnull().sum()

Age                                  0
Gender                               0
Avg_Daily_Screen_Time_hr             0
Primary_Device                       0
Exceeded_Recommended_Limit           0
Educational_to_Recreational_Ratio    0
Health_Impacts                       0
Urban_or_Rural                       0
dtype: int64

In [8]:
df.drop_duplicates(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9668 entries, 0 to 9711
Data columns (total 8 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                9668 non-null   int64
 1   Gender                             9668 non-null   object
 2   Avg_Daily_Screen_Time_hr           9668 non-null   float64
 3   Primary_Device                     9668 non-null   object
 4   Exceeded_Recommended_Limit         9668 non-null   bool
 5   Educational_to_Recreational_Ratio  9668 non-null   float64
 6   Health_Impacts                     9668 non-null   object
 7   Urban_or_Rural                     9668 non-null   object
dtypes: bool(1), float64(2), int64(1), object(4)
memory usage: 613.7+ KB

In [9]:
df.columns=df.columns.str.strip()
df.columns

Index(['Age', 'Gender', 'Avg_Daily_Screen_Time_hr', 'Primary_Device',
       'Exceeded_Recommended_Limit', 'Educational_to_Recreational_Ratio',
       'Health_Impacts', 'Urban_or_Rural'],
      dtype='object')

In [10]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [11]:
df["Age"].unique()

array([14, 11, 18, 15, 12, 17, 10, 13,  9,  8, 16])

In [12]:
def age_group(age):
    if age <=10:
        return "6-10"
    elif age <=15:
        return "11-15"
    else:
        return "16-18"
    
df["Age_Band"]=df["Age"].apply(age_group)
df["Age_Band"].value_counts()

Age_Band
11-15    4399
6-10     2638
16-18    2631
Name: count, dtype: int64

In [13]:
def screen_time_category(screen_time):
    if screen_time <= 3:
        return "Low"
    elif screen_time <= 5:
        return "Medium"
    else:
        return "High"
    
df["Screen_Time_Level"]=df["Avg_Daily_Screen_Time_hr"].apply(screen_time_category)
df["Screen_Time_Level"].value_counts()

Screen_Time_Level
Medium    4678
High      3272
Low       1718
Name: count, dtype: int64

In [14]:
def health_impact_flag(impact):
    if impact == "None":
        return "No risk"
    else:
        return "At risk"
    
df["Health_Risk_Flag"]=df['Health_Impacts'].apply(health_impact_flag)    
df["Health_Risk_Flag"].value_counts()

Health_Risk_Flag
At risk    6488
No risk    3180
Name: count, dtype: int64

In [15]:
def usage_type(row):
    if row>=0.5:
        return "More Educational"
    else:
        return "More Recreational"
df["Usage_Type"]=df["Educational_to_Recreational_Ratio"].apply(usage_type)    
df["Usage_Type"].value_counts()

Usage_Type
More Recreational    8085
More Educational     1583
Name: count, dtype: int64

In [16]:
df.to_csv('Screen_Time_Cleaned.csv', index=False)